Repository opexdev/web-app, pull requests merged in 2022-08, with the labels that each got.

#94 Add landing page
  package.json
  public/locales/fa/translation.json
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/AllMarketContent.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/AllMarketInfo.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/LandingContent.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/GeneralInfo/GeneralInfo.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/MarketInfo.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/MarketInfo.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoCard/MarketInfoCard.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoCard/MarketInfoCard.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoTable/MarketInfoTable.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoTable/MarketInfoTable.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/MarketView.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/MarketView.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/PopularCryptocurrencies/PopularCryptocurrencies.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/PopularCryptocurrencies/PopularCryptocurrencies.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/PopularCryptocurrencies/components/MarketInfoTable/MarketInfoTable.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/PopularCryptocurrencies/components/MarketInfoTable/MarketInfoTable.module.css
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/Spinner/Spinner.module.css
  src/queries/hooks/useGetExchangeInfo.js
  src/queries/hooks/useGetMarketStats.js
  src/queries/hooks/useOverview.js
  src/queries/index.js
  yarn.lock
Labels: enhancement

#97 Release v1.0.0 beta.2
  src/main/Browser/Pages/UserPanel/Sections/Header/components/WalletHeader/WalletHeader.js
  src/main/Browser/Pages/UserPanel/Sections/SubMenu/components/WalletSubMenu/components/WalletListItem/WalletListItem.js
Labels: enhancement

#99 Release v1.0.1-beta.2
  docker-compose.yml
  env-map.js
  package.json
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/AllMarketInfo.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/MarketInfo.js
Labels: bug

#100 Release v1.0.1-beta.2
  docker-compose.yml
  env-map.js
  package.json
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/AllMarketInfo.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/MarketInfo.js
Labels: bug

#101 Release v1.0.2-beta.2
  package.json
  yarn.lock
Labels: enhancement

#102 Release v1.0.2-beta.2
  package.json
  yarn.lock
Labels: enhancement

#104 Fix marketStats bug
  public/locales/en/translation.json
  public/locales/fa/translation.json
  src/components/NullMarketStats/NullMarketStats.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/AllMarketInfo.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/components/AllMarketInfoCard/AllMarketInfoCard.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/AllMarketInfo/components/AllMarketInfoTable/AllMarketInfoTable.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/PriceInfo/PriceInfo.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/PriceInfo/components/MostDecreasedPrice/MostDecreasedPrice.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/PriceInfo/components/MostIncreasedPrice/MostIncreasedPrice.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/VolumeInfo/VolumeInfo.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/VolumeInfo/components/MostTrades/MostTrades.js
  src/main/Browser/Pages/AllMarket/Sections/AllMarketContent/components/VolumeInfo/components/MostVolume/MostVolume.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoCard/MarketInfoCard.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketInfo/components/MarketInfoTable/MarketInfoTable.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/MarketView.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/components/MostDecreasedPrice/MostDecreasedPrice.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/components/MostIncreasedPrice/MostIncreasedPrice.js
  src/main/Browser/Pages/Landing/Sections/LandingContent/components/MarketView/components/MostVolume/MostVolume.js
  src/main/Browser/Pages/Login/components/LoginForm/LoginForm.js
  src/main/Browser/Pages/User/components/ForgetPassword/ForgetPassword.js
Labels: bug

#106 Add estimate wallet value
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  package.json
  public/locales/fa/translation.json
  src/components/ScrollBar/index.js
  src/index.css
  src/main/Browser/Pages/UserPanel/Sections/Content/Content.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/Market.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/LastTrades/LastTrades.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/LastTrades/LastTrades.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/LastTrades/components/LastTradesTable/LastTradesTable.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/LastTrades/components/LastTradesTable/LastTradesTable.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/MyOrders.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/MyOrders.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/components/OpenOrders/OpenOrders.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/components/OrdersHistory/OrdersHistory.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/components/StopMarket/StopMarket.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/MyOrders/components/Trades/Trades.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Order/Order.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Order/Order.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Order/components/BuyOrder/BuyOrder.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Order/components/SellOrder/SellOrder.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/OrderBook.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/OrderBook.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/components/OrderBookTable/OrderBookTable.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/components/OrderBookTable/OrderBookTable.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/components/OrderBookTableSafari/OrderBookTableSafari.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/components/OrderBookTableSafari/OrderBookTableSafari.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/OrderBook/components/OrderBookTooltip/OrderBookTooltip.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Overview/Overview.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Overview/Overview.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/Overview/components/InformationBlock/InformationBlock.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/TradingView/TradingView.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/TradingView/TradingView.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Market/components/TradingView/components/MarketChart/MarketChart.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Wallet/components/DepositWithdraw/components/Withdrawal.js
  src/main/Browser/Pages/UserPanel/Sections/Header/components/WalletHeader/WalletHeader.js
  src/main/Browser/Pages/UserPanel/Sections/SubMenu/components/WalletSubMenu/WalletSubMenu.js
  src/main/Browser/Pages/UserPanel/Sections/SubMenu/components/WalletSubMenu/WalletSubMenu.module.css
  src/main/Browser/Pages/UserPanel/Sections/SubMenu/components/WalletSubMenu/components/WalletBalance/WalletBalance.js
  src/main/Browser/Pages/UserPanel/Sections/SubMenu/components/WalletSubMenu/components/WalletListItem/WalletListItem.js
  src/queries/hooks/useGetFeeForSymbol.js
  src/queries/hooks/useGetUserAssets.js
  src/queries/hooks/useGetUserAssetsEstimatedValue.js
  src/queries/index.js
  yarn.lock
Labels: enhancement

#108 Add currency info api
  public/locales/en/translation.json
  public/locales/fa/translation.json
  src/components/TextInput/TextInput.js
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Wallet/components/DepositWithdraw/DepositWithdraw.module.css
  src/main/Browser/Pages/UserPanel/Sections/Content/components/Wallet/components/DepositWithdraw/components/Withdrawal.js
  src/queries/hooks/useDepositTxs.js
  src/queries/hooks/useGetChartCandlesticks.js
  src/queries/hooks/useGetCurrencyInfo.js
  src/queries/hooks/useGetDepositAddress.js
  src/queries/hooks/useGetExchangeInfo.js
  src/queries/hooks/useGetFeeForSymbol.js
  src/queries/hooks/useGetIPGOpenInvoice.js
  src/queries/hooks/useGetKycStatus.js
  src/queries/hooks/useGetLastPrices.js
  src/queries/hooks/useGetMarketStats.js
  src/queries/hooks/useGetUserActiveSessions.js
  src/queries/hooks/useGetUserAssets.js
  src/queries/hooks/useGetUserAssetsEstimatedValue.js
  src/queries/hooks/useIPGDeposit.js
  src/queries/hooks/useLastTrades.js
  src/queries/hooks/useMyOpenOrders.js
  src/queries/hooks/useMyOrderHistory.js
  src/queries/hooks/useMyTrades.js
  src/queries/hooks/useOrderBook.js
  src/queries/hooks/useOverview.js
  src/queries/hooks/useWithdrawTxs.js
  src/queries/index.js
  yarn.lock
Labels: bug, enhancement

#112 Merge forgot password
  public/locales/en/translation.json
  public/locales/fa/translation.json
  src/main/Browser/Pages/Login/components/ForgetPassword/ForgetPassword.js
  src/main/Browser/Pages/User/components/ForgetPassword/ForgetPassword.js
  src/queries/hooks/useMyTrades.js
  yarn.lock
Labels: bug, enhancement
