Repository opexdev/web-app, pull requests merged in 2022-04, with the labels that each got.

#59 Fix payment callback URL
  src/main/Browser/Sections/Content/components/Wallet/api/wallet.js
Labels: enhancement

#60 Add missing environment variables
  Dockerfile
  Jenkinsfile
  dev.Jenkinsfile
Labels: enhancement

#61 Fix wallet api
  src/main/Browser/Sections/Content/components/Wallet/api/wallet.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/IRT.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/components/CallbackPage/CallbackPage.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdrawTx/DepositWithdrawTx.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdrawTx/components/IRTTx/IRTTx.js
  src/main/Browser/Sections/Header/Header.js
  src/main/Browser/Sections/SubMenu/components/WalletSubMenu/api/wallet.js
  src/pages/Login/Login.js
  src/pages/Login/components/LoginForm/LoginForm.js
Labels: bug

#62 Fix callback component
  public/locales/fa/translation.json
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/IRT.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/components/CallbackPage/CallbackPage.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/components/CallbackPage/CallbackPage.module.css
Labels: enhancement

#63 Hide unfinished components
  src/main/Browser/Sections/Content/components/Settings/components/Authentication/Authentication.js
  src/main/Browser/Sections/Content/components/Settings/components/Authentication/components/PersonalProfileStep/PersonalProfileStep.js
  src/main/Browser/Sections/Content/components/Settings/components/Security/Security.js
  src/main/Browser/Sections/Content/components/Settings/components/Security/components/ActiveSessions/ActiveSessions.js
  src/main/Browser/Sections/Content/components/Settings/components/Security/components/ActiveSessions/components/Details/Details.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Withdrawal.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdrawTx/DepositWithdrawTx.js
  src/main/Browser/Sections/Header/components/MarketHeader/MarketHeader.js
  src/main/Browser/Sections/MainMenu/MainMenu.js
  src/main/Browser/Sections/SubMenu/components/SettingsSubMenu/SettingsSubMenu.js
  src/main/Mobile/Secttions/TheHeader/TheHeader.js
  src/pages/Login/api/auth.js
  src/pages/Login/components/OTPForm/OTPForm.js
Labels: enhancement

#64 Fix deposit address
  src/components/Popup/Popup.js
Labels: bug

#65 Fix error handling in withdraw
  public/locales/fa/translation.json
  src/components/Button/Button.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/DepositWithdraw.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/DepositWithdraw.module.css
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Withdrawal.js
  src/main/Browser/Sections/SubMenu/components/SettingsSubMenu/SettingsSubMenu.js
  src/main/Browser/Sections/SubMenu/components/WalletSubMenu/components/WalletList/WalletList.js
Labels: feature

#67 Fix environment variables passing flow
  Dockerfile
  dev.Jenkinsfile
  docker-compose.yml
Labels: bug

#69 Release v1.0 beta
  public/locales/fa/translation.json
  src/assets/images.js
  src/assets/images/src/testBitcoin.svg
  src/assets/images/src/testEthereumLight.svg
  src/assets/images/src/testTether.svg
  src/components/AdvanceTradingView/DataFeed.js
  src/components/AdvanceTradingView/HistoryProvider.js
  src/main/Browser/Sections/Content/components/Dashboard/components/Order/components/BuyOrder/BuyOrder.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/Deposit.js
  src/main/Browser/Sections/SubMenu/components/Market/api/market.js
  src/pages/Login/components/ForgetPassword/ForgetPassword.js
  src/pages/Login/components/LoginForm/LoginForm.js
  src/pages/Login/components/RegisterForm/RegisterForm.js
  src/store/reducers/authReducer.js
Labels: bug, enhancement

#70 Fix create order
  src/main/Browser/Sections/Content/components/Dashboard/components/Order/api/order.js
  src/main/Browser/Sections/Content/components/Wallet/api/wallet.js
  src/pages/Login/api/auth.js
Labels: bug

#71 Fix axios timeout & testnet config
  public/locales/fa/translation.json
  src/main/Browser/Sections/Content/components/Settings/api/settings.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/Deposit.js
  src/setup/axios/setupAxios.js
Labels: bug, enhancement

#75 Fix v1.0-beta bug
  .env.example
  .yarn/releases/yarn-3.0.0.cjs
  .yarn/releases/yarn-3.2.0.cjs
  .yarnrc.yml
  README.md
  package.json
  public/locales/fa/translation.json
  src/assets/images/src/testEthereumLight.svg
  src/main/Browser/Sections/Content/components/Dashboard/components/MyOrders/components/OpenOrders/OpenOrders.js
  src/main/Browser/Sections/Content/components/Dashboard/components/OrderBook/OrderBook.js
  src/main/Browser/Sections/Content/components/Wallet/api/wallet.js
  src/main/Browser/Sections/Content/components/Wallet/components/DepositWithdraw/components/Deposit/components/IRT/IRT.js
  src/main/Browser/Sections/Header/Header.js
  src/main/Browser/Sections/Header/components/MarketHeader/MarketHeader.js
  src/main/Browser/Sections/Header/components/WalletHeader/WalletHeader.js
  src/main/Browser/Sections/SubMenu/components/Market/Market.js
  src/main/Browser/Sections/SubMenu/components/Market/api/market.js
  src/main/Browser/Sections/SubMenu/components/WalletSubMenu/api/wallet.js
  src/main/Mobile/Mobile.js
  src/pages/Guide/Guide.js
  yarn.lock
Labels: bug
